window.esdocSearchIndex = [
  [
    "generator-ionic-2/core/app/templates/scripts/cordova.es6~cordovacommands",
    "class/core/app/templates/scripts/cordova.es6~CordovaCommands.html",
    "<span>CordovaCommands</span> <span class=\"search-result-import-path\">generator-ionic-2/core/app/templates/scripts/cordova.es6</span>",
    "class"
  ],
  [
    "generator-ionic-2/core/app/index.js~generatorionic2",
    "class/core/app/index.js~GeneratorIonic2.html",
    "<span>GeneratorIonic2</span> <span class=\"search-result-import-path\">generator-ionic-2/core/app/index.js</span>",
    "class"
  ],
  [
    "generator-ionic-2/core/utils/plugins.js~pluginsbook",
    "class/core/utils/Plugins.js~PluginsBook.html",
    "<span>PluginsBook</span> <span class=\"search-result-import-path\">generator-ionic-2/core/utils/Plugins.js</span>",
    "class"
  ],
  [
    "generator-ionic-2/core/utils/validate.js~validate",
    "class/core/utils/Validate.js~Validate.html",
    "<span>Validate</span> <span class=\"search-result-import-path\">generator-ionic-2/core/utils/Validate.js</span>",
    "class"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "external/index.html",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "external/index.html",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "core/app/index.js",
    "file/core/app/index.js.html",
    "core/app/index.js",
    "file"
  ],
  [
    "core/app/index.js~generatorionic2#_addplatforms",
    "class/core/app/index.js~GeneratorIonic2.html#instance-method-_addPlatforms",
    "core/app/index.js~GeneratorIonic2#_addPlatforms",
    "method"
  ],
  [
    "core/app/index.js~generatorionic2#_addplugins",
    "class/core/app/index.js~GeneratorIonic2.html#instance-method-_addPlugins",
    "core/app/index.js~GeneratorIonic2#_addPlugins",
    "method"
  ],
  [
    "core/app/index.js~generatorionic2#_copy",
    "class/core/app/index.js~GeneratorIonic2.html#instance-method-_copy",
    "core/app/index.js~GeneratorIonic2#_copy",
    "method"
  ],
  [
    "core/app/index.js~generatorionic2#_createionicapp",
    "class/core/app/index.js~GeneratorIonic2.html#instance-method-_createIonicApp",
    "core/app/index.js~GeneratorIonic2#_createIonicApp",
    "method"
  ],
  [
    "core/app/index.js~generatorionic2#_getstartprompts",
    "class/core/app/index.js~GeneratorIonic2.html#instance-method-_getStartPrompts",
    "core/app/index.js~GeneratorIonic2#_getStartPrompts",
    "method"
  ],
  [
    "core/app/index.js~generatorionic2#_init",
    "class/core/app/index.js~GeneratorIonic2.html#instance-method-_init",
    "core/app/index.js~GeneratorIonic2#_init",
    "method"
  ],
  [
    "core/app/index.js~generatorionic2#_initcordovaproject",
    "class/core/app/index.js~GeneratorIonic2.html#instance-method-_initCordovaProject",
    "core/app/index.js~GeneratorIonic2#_initCordovaProject",
    "method"
  ],
  [
    "core/app/index.js~generatorionic2#answers",
    "class/core/app/index.js~GeneratorIonic2.html#instance-member-answers",
    "core/app/index.js~GeneratorIonic2#answers",
    "member"
  ],
  [
    "core/app/index.js~generatorionic2#constructor",
    "class/core/app/index.js~GeneratorIonic2.html#instance-constructor-constructor",
    "core/app/index.js~GeneratorIonic2#constructor",
    "method"
  ],
  [
    "core/app/index.js~generatorionic2#createtemplate",
    "class/core/app/index.js~GeneratorIonic2.html#instance-method-createTemplate",
    "core/app/index.js~GeneratorIonic2#createTemplate",
    "method"
  ],
  [
    "core/app/index.js~generatorionic2#filecount",
    "class/core/app/index.js~GeneratorIonic2.html#instance-member-fileCount",
    "core/app/index.js~GeneratorIonic2#fileCount",
    "member"
  ],
  [
    "core/app/index.js~generatorionic2#genprompts",
    "class/core/app/index.js~GeneratorIonic2.html#instance-member-genPrompts",
    "core/app/index.js~GeneratorIonic2#genPrompts",
    "member"
  ],
  [
    "core/app/index.js~generatorionic2#install",
    "class/core/app/index.js~GeneratorIonic2.html#instance-method-install",
    "core/app/index.js~GeneratorIonic2#install",
    "method"
  ],
  [
    "core/app/index.js~generatorionic2#options",
    "class/core/app/index.js~GeneratorIonic2.html#instance-member-options",
    "core/app/index.js~GeneratorIonic2#options",
    "member"
  ],
  [
    "core/app/index.js~generatorionic2#pkg",
    "class/core/app/index.js~GeneratorIonic2.html#instance-member-pkg",
    "core/app/index.js~GeneratorIonic2#pkg",
    "member"
  ],
  [
    "core/app/index.js~generatorionic2#platforms",
    "class/core/app/index.js~GeneratorIonic2.html#instance-member-platforms",
    "core/app/index.js~GeneratorIonic2#platforms",
    "member"
  ],
  [
    "core/app/index.js~generatorionic2#plugins",
    "class/core/app/index.js~GeneratorIonic2.html#instance-member-plugins",
    "core/app/index.js~GeneratorIonic2#plugins",
    "member"
  ],
  [
    "core/app/index.js~generatorionic2#prompting",
    "class/core/app/index.js~GeneratorIonic2.html#instance-method-prompting",
    "core/app/index.js~GeneratorIonic2#prompting",
    "method"
  ],
  [
    "core/app/index.js~generatorionic2#writing",
    "class/core/app/index.js~GeneratorIonic2.html#instance-method-writing",
    "core/app/index.js~GeneratorIonic2#writing",
    "method"
  ],
  [
    "core/app/templates/scripts/cordova.es6",
    "file/core/app/templates/scripts/cordova.es6.html",
    "core/app/templates/scripts/cordova.es6",
    "file"
  ],
  [
    "core/app/templates/scripts/cordova.es6~cordovacommands#args",
    "class/core/app/templates/scripts/cordova.es6~CordovaCommands.html#instance-member-args",
    "core/app/templates/scripts/cordova.es6~CordovaCommands#args",
    "member"
  ],
  [
    "core/app/templates/scripts/cordova.es6~cordovacommands#build",
    "class/core/app/templates/scripts/cordova.es6~CordovaCommands.html#instance-method-build",
    "core/app/templates/scripts/cordova.es6~CordovaCommands#build",
    "method"
  ],
  [
    "core/app/templates/scripts/cordova.es6~cordovacommands#constructor",
    "class/core/app/templates/scripts/cordova.es6~CordovaCommands.html#instance-constructor-constructor",
    "core/app/templates/scripts/cordova.es6~CordovaCommands#constructor",
    "method"
  ],
  [
    "core/app/templates/scripts/cordova.es6~cordovacommands#platform",
    "class/core/app/templates/scripts/cordova.es6~CordovaCommands.html#instance-method-platform",
    "core/app/templates/scripts/cordova.es6~CordovaCommands#platform",
    "method"
  ],
  [
    "core/app/templates/scripts/cordova.es6~cordovacommands#plugin",
    "class/core/app/templates/scripts/cordova.es6~CordovaCommands.html#instance-method-plugin",
    "core/app/templates/scripts/cordova.es6~CordovaCommands#plugin",
    "method"
  ],
  [
    "core/app/templates/scripts/cordova.es6~cordovacommands#prepare",
    "class/core/app/templates/scripts/cordova.es6~CordovaCommands.html#instance-method-prepare",
    "core/app/templates/scripts/cordova.es6~CordovaCommands#prepare",
    "method"
  ],
  [
    "core/app/templates/scripts/cordova.es6~cordovacommands#run",
    "class/core/app/templates/scripts/cordova.es6~CordovaCommands.html#instance-method-run",
    "core/app/templates/scripts/cordova.es6~CordovaCommands#run",
    "method"
  ],
  [
    "core/utils/plugins.js",
    "file/core/utils/Plugins.js.html",
    "core/utils/Plugins.js",
    "file"
  ],
  [
    "core/utils/plugins.js~pluginsbook#api",
    "class/core/utils/Plugins.js~PluginsBook.html#instance-member-api",
    "core/utils/Plugins.js~PluginsBook#api",
    "member"
  ],
  [
    "core/utils/plugins.js~pluginsbook#constructor",
    "class/core/utils/Plugins.js~PluginsBook.html#instance-constructor-constructor",
    "core/utils/Plugins.js~PluginsBook#constructor",
    "method"
  ],
  [
    "core/utils/plugins.js~pluginsbook#getplugins",
    "class/core/utils/Plugins.js~PluginsBook.html#instance-method-getPlugins",
    "core/utils/Plugins.js~PluginsBook#getPlugins",
    "method"
  ],
  [
    "core/utils/plugins.js~pluginsbook#plugins",
    "class/core/utils/Plugins.js~PluginsBook.html#instance-member-plugins",
    "core/utils/Plugins.js~PluginsBook#plugins",
    "member"
  ],
  [
    "core/utils/validate.js",
    "file/core/utils/Validate.js.html",
    "core/utils/Validate.js",
    "file"
  ],
  [
    "core/utils/validate.js~validate.id",
    "class/core/utils/Validate.js~Validate.html#static-method-id",
    "core/utils/Validate.js~Validate.id",
    "method"
  ]
]